config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :families, only: [:index, :show, :new, :create, :edit, :update] do
    resources :publications do
      resources :reviews
    end
    resources :profiles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/couple.rb
class Couple < ApplicationRecord
  belongs_to :blood_user, class_name: "User", foreign_key: :blood_user_id
  belongs_to :out_user, class_name: "User", foreign_key: :out_user_id
  belongs_to :family
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users
  has_many :couples
  has_one_attached :photo
  validates :name, presence: true
end

app/models/liaison.rb
class Liaison < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "User"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  validates :title, presence: true
  validates :content, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_publi,
    against: [:title],
    associated_against: {
      user: [:first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :family
  has_many :publications
  has_ancestry
  has_many :couple_out, class_name: "Couple", foreign_key: :blood_user_id
  has_many :couple_blood, class_name: "Couple", foreign_key: :out_user_id
  has_one_attached :photo
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :city, presence: true
  has_one :parent, through: :liaisons


  include PgSearch::Model
  pg_search_scope :search_by_job_first_last,
    against: [:job, :first_name, :last_name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    families_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :photo, :birth_date, :job])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :photo, :birth_date, :job, :phone])
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def index
    @families = Family.all
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])
    if @family.update(params_family)
      redirect_to families_path
    else
      render :edit
    end
  end

  private

  def params_family
    params.require(:family).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @roots = User.where(family_id: params[:family_id]).roots
    @users = User.find_by_sql(
     "SELECT
        users.id,
        users.ancestry,
        users.first_name,
        users.last_name,
        users.birth_date,
        users.family_id,
        users.job
      FROM users
      ORDER BY
        users.id,
        users.first_name,
        users.last_name,
        users.birth_date DESC
      LIMIT 1000"
      )
    @users_t = User.where(family_id: params[:family_id])
    @couples = Couple.where(family_id: params[:family_id])

    if params[:search].present?
      @users_searched = @users_t.search_by_job_first_last(params[:search]['user'])
    end
  end

  def show
    @user_act = User.where(id: params[:id])
    @user = @user_act.to_a.first
    @roots = User.where(family_id: params[:family_id]).roots
    @users = User.find_by_sql(
     "SELECT
        users.id,
        users.ancestry,
        users.first_name,
        users.last_name,
        users.birth_date,
        users.family_id,
        users.job
      FROM users
      GROUP BY
        users.id,
        users.first_name,
        users.last_name,
        users.birth_date
      LIMIT 1000"
      )
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all

    if params[:search].present?
      @publications = @publications.search_by_publi(params[:search]['publication'])
    end
  end

  def show
    @publication = Publication.find(params[:id])
    @review = Review.new
    @reviews = Review.where(publication: @publication)
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(set_params)
    @user = current_user
    @publication.user = @user
    if @publication.save
      redirect_to family_publications_path(current_user.family)
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    redirect_to family_publications_path
  end

  protected

  def set_params
    params.require(:publication).permit(:title, :content, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(set_params)
    @user = current_user
    @publication = Publication.find(params[:publication_id])
    @review.user = @user
    @review.publication = @publication
    @review.save
    redirect_to family_publication_path(@user.family, @publication)
  end

  protected

  def set_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/families/edit.html.erb
<div class="container fix-footer">
  <%= simple_form_for [@family], remote: true do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.button :submit%>
  <% end %>
</div>

app/views/families/index.html.erb
<div class="container fix-footer">
  <h1 class="bleu-color text-center" style='font-size: 40px;'>Vos familles</h1>
  <div class='mt-3'>
    <% @families.each do |family| %>
      <%= link_to family_profiles_path(family.id), class:'card-family' do  %>
              <p> <%= "Famille #{family.name}" %> </p>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyTree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag 'romantic-tree-shape-with-heart-shaped-leaves.png' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='back'>
  <%= render 'shared/tree' %>
</div>
<div class="container">

</div>

app/views/publications/index.html.erb
<div class="container fix-footer">
  <h1 class="bleu-color text-center" style='font-size: 40px;'>Actualités familiales</h1>
  <div class="d-flex mt-4">
    <div>
      <div class='search-box-publis text-center' style='margin: auto;'>
        <%= link_to 'Publier',  new_family_publication_path(current_user.family), class: 'bleu-button-big' %>
      </div>
      <div class='search-box-publi mt-2'>
      <%= simple_form_for :search, url: family_publications_path, method: "GET", html: { class: 'form-inline mb-2' } do |f| %>
        <%= f.input :publication, input_html: {placeholder: "Recherche..."}, label: false, class:'my-box' %>
      <% end %>
      </div>
    </div>
    <div style= 'width: 75%; margin-bottom: 50px;'>
      <% if @publications.count == 0 %>
          <p class='bleu-color text-center' style='font-style: italic;'>Il n'y a pas encore de contenu publié.</p>
      <% end %>
      <% @publications.order(created_at: :desc).each do |publi| %>
        <%= link_to family_publication_path(current_user.family,publi), class: 'bleu-color' do  %>
          <div class="card-publi" <% unless publi == @publications.order(created_at: :desc).first %> style='margin-top: 25px;' <% end %>>
            <% if publi.photos.attached? %>
              <%= cl_image_tag publi.photos.first.key, class: 'covering image-publi' %>
            <% else %>
              <div class="bleu-background-color blanc-color image-publi">
                <h1 class='text-center' style='padding: 70px 20px; '><%= publi.title %></h1>
              </div>
            <% end %>
              <div class="card-publi-infos">
                <div>
                  <h2><%= publi.title.capitalize %></h2>
                  <p><%= publi.content.first(300) %></p>
                </div>
                <% if publi.user.photo.attached? %>
                  <%= cl_image_tag publi.user.photo.key, class: "card-publi-user avatar-family taupe-border" %>
                <% else %>
                    <div class="card-publi-user avatar-family default taupe-border"> <%= publi.user.first_name.first.upcase %><%= publi.user.last_name.first.upcase %></div>
                <% end %>
              </div>
              <% if publi.user == current_user %>
                <%= link_to family_publication_path(current_user.family, publi), method: 'delete', class: 'taupe-button rounded cross-position' do  %>
                  <i class="fas fa-times blanc-color"></i>
                <% end %>
              <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class='container fix-footer' style='width: 600px;'>
  <h1 class="bleu-color text-center" style='font-size: 40px;'>Votre publication</h1>
  <%= simple_form_for [current_user.family, @publication] do |f| %>
    <%= f.input :title, label: 'Titre', placeholder: 'Ton titre ici...'   %>
    <%= f.input :content,as: :text, label: 'Contenu', data: { emojiable: true }, placeholder: 'Ton texte ici...'  %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, label: 'Ajouter des images :' %>
    <div class='text-center mb-3'>
      <%= f.button :submit, 'Publier', class: 'bleu-button px-2' %>
    </div>

  <% end %>
</div>

app/views/publications/show.html.erb
<div class="container fix-footer">
  <div class="publi-show blanc-background-color">
    <h1> <%= @publication.title %></h1>
    <div class="d-flex align-items-center mt-4">
      <% if @publication.user.photo.attached? %>
        <%= cl_image_tag @publication.user.photo.key, class: 'avatar-family-small' %>
      <% else %>
        <div class="avatar-family-small default-small"> <%= @publication.user.first_name.first.upcase %><%= @publication.user.last_name.first.upcase %></div>
      <% end %>
    <p style='font-style: italic; margin-bottom: 0px;' class='ml-3'>Publié le <%= @publication.created_at.strftime('%d/%m/%y') %> par <%= @publication.user.first_name %> <%= @publication.user.last_name %> </p>
    </div>
    <div class='mt-4'>
      <p style='text-align: justify;'> <%= @publication.content %></p>
    </div>
    <div id="slider">
        <% if @publication.photos.count == 1 %>
            <%= cl_image_tag @publication.photos[0].key, class: 'only-im' %>
        <% elsif @publication.photos.count == 2 %>
          <figure>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[1].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[1].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
          </figure>
        <% elsif @publication.photos.count == 3 %>
          <figure>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[1].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[2].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[1].key, class: 'car-image' %>
          </figure>
        <% elsif @publication.photos.count == 4 %>
          <figure>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[1].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[2].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[3].key, class: 'car-image' %>
            <%= cl_image_tag @publication.photos[0].key, class: 'car-image' %>
          </figure>
        <% elsif @publication.photos.count == 5 %>
          <figure>
            <% @publication.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: 'car-image' %>
            <% end %>
          </figure>
        <% end %>
    </div>
    <div class="reviews-area">
      <h2 class='text-center mt-5 mb-3'>Réactions</h2>
      <% @reviews.each do |review| %>
        <div class="d-flex align-items-center review-one">
        <% if review.user.photo.attached? %>
          <%= cl_image_tag review.user.photo.key, class: 'avatar-family-small' %>
        <% else %>
          <div class="avatar-family-small default-small"> <%= review.user.first_name.first.upcase %><%= review.user.last_name.first.upcase %></div>
        <% end %>
        <p class='ml-3'> <%= review.content %> </p>
        <p style='margin-left: auto; font-style: italic; font-size: 11px;'> par <%= review.user.first_name + ' ' + review.user.last_name %> le <%= review.created_at.strftime('%d/%m/%y') %> </p>
        </div>
      <% end %>
    </div>
    <div class="create-review mt-3">
      <%= simple_form_for [current_user.family, @publication, @review], remote: true do |f|%>
        <%= f.input :content,as: :text, label: false %>
        <div class='text-center mb-3'>
          <%= f.button :submit, 'Réagir', class: 'bleu-button px-2' %>
        </div>
      <% end %>
    </div>
    <div class="text-center mt-3">
      <%= link_to 'Retour', family_publications_path(current_user.family), class: 'taupe-button'  %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-setting">
  <div>
    <%= render 'shared/small_tree' %>
    <p class='blanc-color text-center' style='font-size: 6px; font-style: italic;'>2021</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_user == nil %>
  <div class="navbar-lewagon justify-content-end">
    <%= link_to "S'identifier", user_session_path %>
  </div>
<% else %>
  <div class="navbar-lewagon justify-content-center" style='position: relative;'>
    <%= link_to "Arbre", families_path, class: 'hover hover-3' %>
    <%= link_to "Actualités", family_publications_path(current_user.family), class: 'hover hover-3' %>
    <%= link_to "Mon profil", family_profile_path(current_user.family, current_user), class: 'hover hover-3' %>
    <div class='justify-self-end' style='position: absolute; top: 17px; right: 0px;'>
      <%= link_to "Déconnecter", destroy_user_session_path, method: :delete, class: 'taupe-button', style: 'font-size: 10px;' %>
    </div>
  </div>
<% end %>